### ISSUE TITLE
Add Nominatim Boundary Search

### ISSUE THREAD

**Issue by karsonkevin2** [russbiggs/swimming-pools#6]
Hi, I like the project. I think it presents a very interesting way of viewing objects. I forked the project and tried it out with some of my own data. For me, that meant having to play around with the code for a few hours since it didn't work initially and I am not familiar with JavaScript/HTML.

Adding a landing page with a Nominatim search similar to https://anvaka.github.io/city-roads/ would be a great improvement. This would make your project more interesting to share with people as they could explore the data in their home cities.

**Comment by russbiggs** [comment]
Glad you found it interesting. I really enjoy the city-roads tool (as did many it was really popular!). Short of storing all the protobuf like they are doing (and keeping that up-to-date for US (or world?), I can definitely flesh out the readme and smooth out the edges a bit. All the pieces to fully recreate are in the repo but not necessarily coherent.

**Comment by russbiggs** [comment]
@karsonkevin2 i've updated the readme, so hopefully its easy to get up and running if someone else wants to build their own copy.
